proxmox:
    hosts:
        10.1.4.22:
esphome:
    hosts:
        10.1.2.5:
dhcp:
    children:
        primary:
            hosts:
                10.1.3.3:
        standby:
            hosts:
                10.1.3.4:
dhcp_admin:
    hosts:
        10.1.3.13:
dns_auth:
    hosts:
        10.1.3.5:
        10.1.3.6:
dns_recurse:
    hosts:
        10.1.3.7:
        10.1.3.8:
dns_dist:
    hosts:
        10.1.3.9:
        10.1.3.10:
dns_admin:
    hosts:
        10.1.3.11:
        10.1.3.12:
mariadb_cluster:
    hosts:
        10.1.3.115:
        10.1.3.116:
        10.1.3.17:
        10.1.3.18:
        10.1.3.19:
mariadb_maxscale:
    hosts:
        10.1.3.20:
        10.1.3.21:
postgresql:
    hosts:
        10.1.3.22:
        10.1.3.23:
        10.1.3.24:
jellyfin:
    hosts:
        10.1.3.30:
watchtower:
    hosts:
        10.1.3.31:
arr:
    hosts:
        10.1.3.32:
immich:
    hosts:
        10.1.3.33:
homepage:
    hosts:
        10.1.3.35:
nginx_proxy:
    hosts:
        10.1.3.40:
        10.1.3.41:
        10.1.3.42:
haproxy:
    hosts:
        10.1.3.45:
        10.1.3.46:
web:
    children:
        nginx:
            hosts:
        apache:
            hosts:
                10.1.3.43:
                10.1.3.44:
vms:
    hosts:
        10.1.3.15:
        10.1.3.16:
        10.1.3.52:
        10.1.3.53:
        10.1.3.54:
        10.1.3.57:
        10.1.3.58:
containers:
    children:
        esphome:
        dhcp:
        dhcp_admin:
        dns_auth:
        dns_recurse:
        dns_dist:
        dns_admin:
        mariadb_cluster:
        mariadb_maxscale:
        postgresql:
        jellyfin:
        watchtower:
        arr:
        immich:
        homepage:
        nginx_proxy:
        haproxy:
        web:
