---
- name: Test Playbook
  hosts: all
  tasks:
    - name: Remove unnecessary packages
      ansible.builtin.package:
        state: absent
        name: '{{ remove-packages }}''

    #- name: Display variable
    #  ansible.builtin.debug:
    #    var: "{{ variable }}"
