---
- name: Test Playbook
  hosts: all
  tasks:
    - name: Apply Glances API Web Server service
      ansible.builtin.template:
        src: glances-api.service.j2
        dest: /etc/systemd/system/glances-api.service

    - name: Enable and Start Glances API Web Server
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: glances-api.service
    #- name: Display variable
    #  ansible.builtin.debug:
    #    var: "{{ variable }}"
