---
- name: Test Playbook
  hosts: all
  tasks:
    #- name: Display variable
    #  ansible.builtin.debug:
    #    var: "{{ variable }}"

    - name: Install NetData
      ansible.builtin.script: 
        cmd: netdata.sh "{{ netdata_claim_token }}" "{{ netdata_room_token }}"

    - name: Restart netdata service
      ansible.builtin.systemd_service:
        name: netdata.service
        state: restarted
