---
- name: Test Playbook
  hosts: all
  tasks:
    #- name: Display variable
    #  ansible.builtin.debug:
    #    var: "{{ variable }}"

    - name: Remove netdata stream.conf
      ansible.builtin.file:
        path: /etc/netdata/stream.conf
        state: absent

    - name: Restart netdata service
      ansible.builtin.systemd_service:
        name: netdata.service
        state: restarted
