---
- hosts: all
  tasks:
      - name: Install EPEL on Rocky Server
        ansible.builtin.yum:
            state: present
            pkg: "epel-release"
        when:
        - ansible_facts['distribution'] == "Rocky"

      - name: Install packages on Debian Servers
        ansible.builtin.package:
            state: latest
            name: "{{ packages }}"
