---
- hosts: all
  tasks:
      - name: Install packages on Debian Servers
        ansible.builtin.apt:
            update_cache: yes
            state: latest
            pkg: "{{ packages }}"
        when:
        - ansible_facts['distribution'] == "Debian"

      - name: Install packages on Rocky Servers
        ansible.builtin.yum:
            state: latest
            name: "{{ packages }}"
        when:
        - ansible_facts['distribution'] == "Rocky"

