- name: Set Zabbix Agent passive server
  ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      search_string: 'Server='
      line: Server=10.1.3.17

- name: Set Zabbix Agent active server
  ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      search_string: 'ServerActive='
      line: ServerActive=10.1.3.17

- name: Set Zabbix Agent hostname
  ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      search_string: 'Hostname='
      line: Hostname={{ ansible_facts['fqdn'] }}