- name: Enroll TPM - Create temporary passphrase file
  ansible.builtin.lineinfile:
    path: /tmp/passphrase
    line: "{{ encryption_passphrase }}"
    mode: '0700'
    create: yes
  
- name: Enroll TPM - Enroll tpm2 in primary disk
  ansible.builtin.command:
    argv:
      - /usr/bin/systemd-cryptenroll
      - /dev/vda3
      - --unlock-key-file=/tmp/passphrase
      - --tpm2-device=auto
      - --tpm2-pcrs=0+7
#  when:
#    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

#- name: Enroll TPM - Enroll tpm2 in primary disk on Rocky servers
#  ansible.builtin.command:
#    argv:
#      - /usr/bin/clevis
#      - luks
#      - bind
#      - -d
#      - /dev/vda3
#      - tpm2
#      - '{"hash":"sha256","key":"rsa","pcr_bank":"sha256","pcr_ids":"0,7"}'
#  when:
#    - ansible_facts['distribution'] == "Rocky"

- name: Enroll TPM - Remove temporary passphrase file
  ansible.builtin.file:
    path: /tmp/passphrase
    state: absent

- name: Enroll TPM - Add tpm2 modules to Dracut Config on Ubuntu and Debian servers
  ansible.builtin.lineinfile:
    path: /etc/dracut.conf.d/tpm2_auto_unlock.conf
    line: 'add_dracutmodules+=" tpm2-tss crypt "'
    create: yes
  when: 
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Enabled tpm2 auto unlock on Ubuntu and Debian servers
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    search_string: 'GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="rd.auto rd.luks=1"'
  when: 
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Remove entry from /etc/crypttab on Ubuntu and Debian servers
  ansible.builtin.lineinfile:
    path: /etc/crypttab
    regex: ".*"
    state: absent
  when: 
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Regenerate Dracut on Ubuntu and Debian servers
  ansible.builtin.command:
    argv:
      - /usr/bin/dracut
      - -f
  when: 
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Update Grub on Ubuntu and Debian servers
  ansible.builtin.command:
    argv:
      - /usr/bin/update-grub
  when: 
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")