- name: Enable IPv4 Packet Forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.ipv4.ip_forward = 1
    create: true
    mode: "0777"

- name: Apply IPv4 Packet Forwarding
  ansible.builtin.command:
    argv:
      - sysctl
      - --system
  register: output
  changed_when: output.rc == 0
