- name: Enable IPv4 Forwarding
  ansible.builtin.import_tasks: enable_ipv4_forwarding.yml

- name: Install Docker Engine on Debian and Ubuntu Servers
  ansible.builtin.import_tasks: install_docker_engine_debian.yml
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Install Docker Engine on Rocky Linux Servers
  ansible.builtin.import_tasks: install_docker_engine_rocky.yml
  when:
    - ansible_facts['distribution'] == "Rocky"

- name: Install OVN_Kubernetes
  ansible.builtin.import_tasks: install_ovn_kubernetes.yml

- name: Install Kubernetes Packages
  ansible.builtin.import_tasks: install_kubernetes_packages.yml

#- name: Apply Kubelet.conf Template
#  ansible.builtin.import_tasks: apply_kubelet_config.yml
