- name: Install NetData
  ansible.builtin.script: 
    cmd: netdata.sh --non-interactive --stable-channel --disable-telemetry

- name: Upgrade Packages
  ansible.builtin.import_tasks: upgrade_packages.yml

- name: Configure SSHD
  ansible.builtin.import_tasks: sshd_config.yml

- name: Configure SSH Keys
  ansible.builtin.import_tasks: ssh_keys.yml

- name: Create cockpit disallowed users file if it doesn't exist
  ansible.builtin.lineinfile:
    path: /etc/cockpit/disallowed-users
    line: '# List of users which are not allowed to login to Cockpit'
    create: true
    mode: "0644"

- name: Remove entry of root in cockpit disallowed users
  ansible.builtin.lineinfile:
    path: /etc/cockpit/disallowed-users
    regexp: '^root'
    state: absent

- name: Create motd file if it does not exist
  ansible.builtin.lineinfile:
    path: /etc/motd
    line: temp
    create: true
    mode: "0644"

- name: Remove text in motd file
  ansible.builtin.lineinfile:
    path: /etc/motd
    regexp: '.*'
    state: absent

- name: Enable and Start cockpit.socket
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: cockpit.socket