- name: Remove initial delete-me user
  ansible.builtin.user:
    state: absent
    force: true
    name: delete-me

- name: Update Apt cache
  ansible.builtin.apt:
    update_cache: true
    state: present

- name: Install packages
  block:
    - name: Install packages
      ansible.builtin.package:
        state: present
        name: "{{ debian_packages }}"
      when:
        - ansible_facts["distribution"] == "Debian"

    - name: Install packages
      ansible.builtin.package:
        state: present
        name: "{{ ubuntu_packages }}"
      when:
        - ansible_facts["distribution"] == "Ubuntu"

- name: Run tasks for all_distros
  ansible.builtin.import_tasks: all_distros.yml

- name: Setup TPM Auto-Unlock
  when:
    - inventory_hostname in lookup("inventory_hostnames", "vms")
  block:
    - name: \[Setup TPM Auto-Unlock\] Enroll tpm2 in primary disk - Run systemd-tty-ask-password-agent on the system
      ansible.builtin.raw: "echo 'tmp' | /usr/bin/systemd-cryptenroll /dev/sda3 --tpm2-device=auto --tpm2-pcrs=0+7"
      args:
        executable: /bin/bash
      register: output
      changed_when: output.rc == 0

    - name: \[Setup TPM Auto-Unlock\] Add tpm2 modules to Dracut Config
      ansible.builtin.lineinfile:
        path: /etc/dracut.conf.d/tpm2_auto_unlock.conf
        line: 'add_dracutmodules+=" tpm2-tss crypt "'
        create: true
        mode: "0600"
      register: output
      changed_when: output == "*context changed"

    - name: \[Setup TPM Auto-Unlock\] Configure Grub
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        search_string: "GRUB_CMDLINE_LINUX="
        line: 'GRUB_CMDLINE_LINUX="rd.auto rd.luks=1"'

    - name: \[Setup TPM Auto-Unlock\] Remove entry from /etc/crypttab
      ansible.builtin.lineinfile:
        path: /etc/crypttab
        regex: ".*"
        state: absent

    - name: \[Setup TPM Auto-Unlock\] Regenerate Dracut
      ansible.builtin.command:
        argv:
          - /usr/bin/dracut
          - -f
      register: output
      changed_when: output.rc == 0

    - name: \[Setup TPM Auto-Unlock\] Update Grub on Ubuntu and Debian servers
      ansible.builtin.command:
        argv:
          - /usr/sbin/update-grub
      register: output
      changed_when: output.rc == 0

- name: Restart SSHD
  block:
    - name: Restart SSHD
      ansible.builtin.systemd_service:
        state: restarted
        name: sshd.service
      when:
        - ansible_facts["distribution"] != "Ubuntu"

    - name: Restart SSHD
      ansible.builtin.systemd_service:
        state: restarted
        name: ssh.service
      when:
        - ansible_facts["distribution"] == "Ubuntu"
