- name: Enroll TPM - Enroll tpm2 in primary disk - Run systemd-tty-ask-password-agent on the system
  ansible.builtin.raw: 'echo "tmp" | /usr/bin/systemd-cryptenroll /dev/sda3 --tpm2-device=auto --tpm2-pcrs=0+7'
  args:
    executable: /bin/bash
  register: output
  changed_when: output.rc == 0
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Enroll tpm2 in primary disk on Rocky servers
  ansible.builtin.command:
    argv:
      - /usr/bin/clevis
      - luks
      - bind
      - -d
      - /dev/sda3
      - tpm2
      - '{"hash":"sha256","key":"rsa","pcr_bank":"sha256","pcr_ids":"0,7"}'
    stdin: "{{ encryption_passphrase }}"
  register: output
  changed_when: output.rc == 0
  creates: /root/tpm_enrolled
  when:
    - (ansible_facts['distribution'] == "Rocky") or (ansible_facts['distribution'] == "RedHat")

- name: Enroll TPM - Add tpm2 modules to Dracut Config on Ubuntu and Debian servers
  ansible.builtin.lineinfile:
    path: /etc/dracut.conf.d/tpm2_auto_unlock.conf
    line: 'add_dracutmodules+=" tpm2-tss crypt "'
    create: true
    mode: "0600"
  register: output
  changed_when: output == "*context changed"
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Enabled tpm2 auto unlock on Ubuntu and Debian servers
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    search_string: 'GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="rd.auto rd.luks=1"'
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Remove entry from /etc/crypttab on Ubuntu and Debian servers
  ansible.builtin.lineinfile:
    path: /etc/crypttab
    regex: ".*"
    state: absent
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Regenerate Dracut on Ubuntu and Debian servers
  ansible.builtin.command:
    argv:
      - /usr/bin/dracut
      - -f
  register: output
  changed_when: output.rc == 0
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Update Grub on Ubuntu and Debian servers
  ansible.builtin.command:
    argv:
      - /usr/sbin/update-grub
  register: output
  changed_when: output.rc == 0
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Enroll TPM - Install clevis-dracut on Rocky servers
  ansible.builtin.dnf:
    state: present
    pkg: "clevis-dracut"
  when:
    - (ansible_facts['distribution'] == "Rocky") or (ansible_facts['distribution'] == "RedHat")

- name: Enroll TPM - Regenerate Dracut on Rocky servers
  ansible.builtin.command:
    argv:
      - dracut
      - -fv
      - --regenerate-all
  register: output
  changed_when: output.rc == 0
  when:
    - (ansible_facts['distribution'] == "Rocky") or (ansible_facts['distribution'] == "RedHat")
