- name: Add Docker-CE RHEL Repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"
    owner: root
    group: root
  when:
    - ansible_facts['distribution'] == "Rocky"

- name: Install Docker Packages
  ansible.builtin.dnf:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add Docker TCP Socket
  ansible.builtin.template:
    src: docker.service.d_override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Enable and Start Docker Socket
  ansible.builtin.systemd:
    name: docker.socket
    state: started
    enabled: true

- name: Install Komodo Periphery
  ansible.builtin.script:
    cmd: setup-periphery.sh
    creates: /etc/systemd/system/periphery.service

- name: Configure Komodo Periphery
  ansible.builtin.template:
    src: peripher.config.toml.j2
    dest: /etc/komodo/periphery.config.toml
    mode: "0644"
    owner: root
    group: root

- name: Enable and Start Komodo Periphery
  ansible.builtin.systemd_service:
    name: periphery.service
    state: started
    enabled: true