- name: Run Rocky-based tasks
  ansible.builtin.import_tasks: rocky.yml
  when:
    - ansible_facts['distribution'] == "Rocky"

- name: Run Debian-based tasks
  ansible.builtin.import_tasks: debian.yml
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")
