#- name: Set SELINUX to Permissive
#  ansible.posix.selinux:
#    policy: 'targeted'
#    state: 'permissive'
#  when:
#    - ansible_facts['virtualization_type'] == "kvm"

- name: Configure Rocky Repos
  block:
    - name: Configure rocky-addons.repo
      ansible.builtin.template:
        src: rocky-addons.repo.j2
        dest: /etc/yum.repos.d/rocky-addons.repo
        mode: '0644'
        owner: 'root'
        group: 'root'

    - name: Configure rocky-devel.repo
      ansible.builtin.template:
        src: rocky-devel.repo.j2
        dest: /etc/yum.repos.d/rocky-devel.repo
        mode: '0644'
        owner: 'root'
        group: 'root'

    - name: Configure rocky-extras.repo
      ansible.builtin.template:
        src: templates/rocky-extras.repo.j2
        dest: /etc/yum.repos.d/rocky-extras.repo
        mode: '0644'
        owner: 'root'
        group: 'root'

    - name: Configure rocky.repo
      ansible.builtin.template:
        src: templates/rocky.repo.j2
        dest: /etc/yum.repos.d/rocky.repo
        mode: '0644'
        owner: 'root'
        group: 'root'

- name: Install EPEL
  ansible.builtin.dnf:
    state: present
    pkg: epel-release

- name: Install packages
  ansible.builtin.package:
    state: present
    name: "{{ rocky_packages }}"

- name: Run tasks for all_distros
  ansible.builtin.import_tasks: all_distros.yml

- name: Disable and Mask firewalld
  when:
    - ansible_facts['virtualization_type'] == "kvm"
  ansible.builtin.systemd_service:
    state: stopped
    enabled: false
    masked: true
    name: firewalld.service

- name: Setup TPM Auto-Unlock
  when:
    - ansible_facts['virtualization_type'] == "kvm"
  block:
    - name: \[Setup TPM Auto-Unlock\] Enroll tpm2 in primary disk on Rocky servers
      ansible.builtin.command:
        argv:
          - /usr/bin/clevis
          - luks
          - bind
          - -d
          - /dev/sda3
          - tpm2
          - '{"hash":"sha256","key":"rsa","pcr_bank":"sha256","pcr_ids":"0,7"}'
        stdin: "{{ encryption_passphrase }}"
      register: output
      changed_when: output.rc == 0

    - name: \[Setup TPM Auto-Unlock\] Install clevis-dracut on Rocky servers
      ansible.builtin.dnf:
        state: present
        pkg: "clevis-dracut"

    - name: \[Setup TPM Auto-Unlock\] Regenerate Dracut on Rocky servers
      ansible.builtin.command:
        argv:
          - dracut
          - -fv
          - --regenerate-all
      register: output
      changed_when: output.rc == 0

- name: Restart SSHD
  ansible.builtin.systemd_service:
    state: restarted
    name: sshd.service
