- name: Update apt repo and cache on Debian and Ubuntu Servers
  ansible.builtin.apt:
    update_cache: true
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Upgrade all packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Check if a reboot is needed on Debian and Ubuntu Servers
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Reboot the box if kernel updated on Debian and Ubuntu Servers
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")
    - reboot_required_file.stat.exists == "True"

- name: Clean and Remove unused packages on Debian and Ubuntu Servers
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
  when:
    - (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: Remove unused packages on Rocky Servers
  ansible.builtin.dnf:
    autoremove: true
  when:
    - ansible_facts['distribution'] == "Rocky"
